PROFILE_NAMES = Generic DEVICE_asus_rt-ac3100 DEVICE_asus_rt-ac56u DEVICE_asus_rt-ac68u DEVICE_asus_rt-ac87u DEVICE_asus_rt-ac88u DEVICE_asus_rt-n18u DEVICE_buffalo_wxr-1900dhp DEVICE_buffalo_wzr-600dhp2 DEVICE_buffalo_wzr-900dhp DEVICE_buffalo_wzr-1750dhp DEVICE_dlink_dir-885l DEVICE_dlink_dwl-8610ap DEVICE_linksys_ea6300-v1 DEVICE_linksys_ea6500-v2 DEVICE_linksys_ea9200 DEVICE_linksys_ea9500 DEVICE_luxul_abr-4500 DEVICE_luxul_xap-1610 DEVICE_luxul_xbr-4500 DEVICE_luxul_xwr-3150 DEVICE_meraki_mr26 DEVICE_meraki_mr32 DEVICE_netgear_r6250 DEVICE_netgear_r6300-v2 DEVICE_netgear_r7000 DEVICE_netgear_r7900 DEVICE_netgear_r8000 DEVICE_netgear_r8500 DEVICE_smartrg_sr400ac DEVICE_phicomm_k3 DEVICE_tenda_ac9
Generic_NAME:=Broadcom SoC, BCM43xx WiFi (b43, brcmfmac, default)
Generic_HAS_IMAGE_METADATA:=0
Generic_PACKAGES:=kmod-b43 kmod-brcmfmac
DEVICE_asus_rt-ac3100_NAME:=ASUS RT-AC3100
DEVICE_asus_rt-ac3100_HAS_IMAGE_METADATA:=0
DEVICE_asus_rt-ac3100_SUPPORTED_DEVICES:=asus,rt-ac3100
DEVICE_asus_rt-ac3100_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-4366b1-pcie wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-4366c0-pcie kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_asus_rt-ac56u_NAME:=ASUS RT-AC56U
DEVICE_asus_rt-ac56u_HAS_IMAGE_METADATA:=0
DEVICE_asus_rt-ac56u_SUPPORTED_DEVICES:=asus,rt-ac56u
DEVICE_asus_rt-ac56u_PACKAGES:=wpad-basic-mbedtls kmod-b43 kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_asus_rt-ac68u_NAME:=ASUS RT-AC68U
DEVICE_asus_rt-ac68u_HAS_IMAGE_METADATA:=0
DEVICE_asus_rt-ac68u_SUPPORTED_DEVICES:=asus,rt-ac68u
DEVICE_asus_rt-ac68u_PACKAGES:=kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3
DEVICE_asus_rt-ac87u_NAME:=ASUS RT-AC87U
DEVICE_asus_rt-ac87u_HAS_IMAGE_METADATA:=0
DEVICE_asus_rt-ac87u_SUPPORTED_DEVICES:=asus,rt-ac87u
DEVICE_asus_rt-ac87u_PACKAGES:=kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3
DEVICE_asus_rt-ac88u_NAME:=ASUS RT-AC88U
DEVICE_asus_rt-ac88u_HAS_IMAGE_METADATA:=0
DEVICE_asus_rt-ac88u_SUPPORTED_DEVICES:=asus,rt-ac88u
DEVICE_asus_rt-ac88u_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-4366b1-pcie wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-4366c0-pcie kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_asus_rt-n18u_NAME:=ASUS RT-N18U
DEVICE_asus_rt-n18u_HAS_IMAGE_METADATA:=0
DEVICE_asus_rt-n18u_SUPPORTED_DEVICES:=asus,rt-n18u
DEVICE_asus_rt-n18u_PACKAGES:=kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3
DEVICE_buffalo_wxr-1900dhp_NAME:=Buffalo WXR-1900DHP
DEVICE_buffalo_wxr-1900dhp_HAS_IMAGE_METADATA:=0
DEVICE_buffalo_wxr-1900dhp_SUPPORTED_DEVICES:=buffalo,wxr-1900dhp
DEVICE_buffalo_wxr-1900dhp_PACKAGES:=kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3
DEVICE_buffalo_wzr-600dhp2_NAME:=Buffalo WZR-600DHP2
DEVICE_buffalo_wzr-600dhp2_HAS_IMAGE_METADATA:=0
DEVICE_buffalo_wzr-600dhp2_SUPPORTED_DEVICES:=buffalo,wzr-600dhp2
DEVICE_buffalo_wzr-600dhp2_PACKAGES:=wpad-basic-mbedtls kmod-b43 kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport iwinfo
DEVICE_buffalo_wzr-900dhp_NAME:=Buffalo WZR-900DHP
DEVICE_buffalo_wzr-900dhp_HAS_IMAGE_METADATA:=1
DEVICE_buffalo_wzr-900dhp_SUPPORTED_DEVICES:=buffalo,wzr-900dhp
DEVICE_buffalo_wzr-900dhp_PACKAGES:=wpad-basic-mbedtls kmod-b43 kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_buffalo_wzr-1750dhp_NAME:=Buffalo WZR-1750DHP
DEVICE_buffalo_wzr-1750dhp_HAS_IMAGE_METADATA:=0
DEVICE_buffalo_wzr-1750dhp_SUPPORTED_DEVICES:=buffalo,wzr-1750dhp
DEVICE_buffalo_wzr-1750dhp_PACKAGES:=wpad-basic-mbedtls kmod-b43 kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_dlink_dir-885l_NAME:=D-Link DIR-885L
DEVICE_dlink_dir-885l_HAS_IMAGE_METADATA:=0
DEVICE_dlink_dir-885l_SUPPORTED_DEVICES:=dlink,dir-885l
DEVICE_dlink_dir-885l_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-4366b1-pcie kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_dlink_dwl-8610ap_NAME:=D-Link DWL-8610AP
DEVICE_dlink_dwl-8610ap_HAS_IMAGE_METADATA:=0
DEVICE_dlink_dwl-8610ap_SUPPORTED_DEVICES:=dlink,dwl-8610ap
DEVICE_dlink_dwl-8610ap_PACKAGES:=wpad-basic-mbedtls kmod-b43 iwinfo
DEVICE_linksys_ea6300-v1_NAME:=Linksys EA6300 v1
DEVICE_linksys_ea6300-v1_HAS_IMAGE_METADATA:=0
DEVICE_linksys_ea6300-v1_SUPPORTED_DEVICES:=linksys,ea6300-v1
DEVICE_linksys_ea6300-v1_PACKAGES:=wpad-basic-mbedtls kmod-b43 kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_linksys_ea6500-v2_NAME:=Linksys EA6500 v2
DEVICE_linksys_ea6500-v2_HAS_IMAGE_METADATA:=0
DEVICE_linksys_ea6500-v2_SUPPORTED_DEVICES:=linksys,ea6500-v2
DEVICE_linksys_ea6500-v2_PACKAGES:=wpad-basic-mbedtls kmod-b43 kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_linksys_ea9200_NAME:=Linksys EA9200 v1
DEVICE_linksys_ea9200_HAS_IMAGE_METADATA:=0
DEVICE_linksys_ea9200_SUPPORTED_DEVICES:=linksys,ea9200
DEVICE_linksys_ea9200_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-43602a1-pcie kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_linksys_ea9500_NAME:=Linksys EA9500
DEVICE_linksys_ea9500_HAS_IMAGE_METADATA:=0
DEVICE_linksys_ea9500_SUPPORTED_DEVICES:=linksys,ea9500
DEVICE_linksys_ea9500_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-4366c0-pcie kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_luxul_abr-4500_NAME:=Luxul ABR-4500
DEVICE_luxul_abr-4500_HAS_IMAGE_METADATA:=0
DEVICE_luxul_abr-4500_SUPPORTED_DEVICES:=luxul,abr-4500
DEVICE_luxul_abr-4500_PACKAGES:=kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3
DEVICE_luxul_xap-1610_NAME:=Luxul XAP-1610
DEVICE_luxul_xap-1610_HAS_IMAGE_METADATA:=0
DEVICE_luxul_xap-1610_SUPPORTED_DEVICES:=luxul,xap-1610
DEVICE_luxul_xap-1610_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-4366c0-pcie iwinfo
DEVICE_luxul_xbr-4500_NAME:=Luxul XBR-4500
DEVICE_luxul_xbr-4500_HAS_IMAGE_METADATA:=0
DEVICE_luxul_xbr-4500_SUPPORTED_DEVICES:=luxul,xbr-4500
DEVICE_luxul_xbr-4500_PACKAGES:=kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3
DEVICE_luxul_xwr-3150_NAME:=Luxul XWR-3150
DEVICE_luxul_xwr-3150_HAS_IMAGE_METADATA:=0
DEVICE_luxul_xwr-3150_SUPPORTED_DEVICES:=luxul,xwr-3150
DEVICE_luxul_xwr-3150_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-4366c0-pcie kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_meraki_mr26_NAME:=Meraki MR26
DEVICE_meraki_mr26_HAS_IMAGE_METADATA:=1
DEVICE_meraki_mr26_SUPPORTED_DEVICES:=meraki,mr26
DEVICE_meraki_mr26_PACKAGES:=wpad-basic-mbedtls kmod-b43 kmod-i2c-bcm-iproc kmod-eeprom-at24 kmod-hwmon-ina2xx kmod-leds-uleds nu801 iwinfo
DEVICE_meraki_mr32_NAME:=Meraki MR32
DEVICE_meraki_mr32_HAS_IMAGE_METADATA:=1
DEVICE_meraki_mr32_SUPPORTED_DEVICES:=meraki,mr32
DEVICE_meraki_mr32_PACKAGES:=wpad-basic-mbedtls kmod-b43 kmod-i2c-bcm-iproc kmod-eeprom-at24 kmod-leds-pwm kmod-hwmon-ina2xx kmod-bluetooth iwinfo
DEVICE_netgear_r6250_NAME:=NETGEAR R6250
DEVICE_netgear_r6250_HAS_IMAGE_METADATA:=0
DEVICE_netgear_r6250_SUPPORTED_DEVICES:=netgear,r6250
DEVICE_netgear_r6250_PACKAGES:=wpad-basic-mbedtls kmod-b43 kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_netgear_r6300-v2_NAME:=NETGEAR R6300 v2
DEVICE_netgear_r6300-v2_HAS_IMAGE_METADATA:=0
DEVICE_netgear_r6300-v2_SUPPORTED_DEVICES:=netgear,r6300-v2
DEVICE_netgear_r6300-v2_PACKAGES:=wpad-basic-mbedtls kmod-b43 kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_netgear_r7000_NAME:=NETGEAR R7000
DEVICE_netgear_r7000_HAS_IMAGE_METADATA:=0
DEVICE_netgear_r7000_SUPPORTED_DEVICES:=netgear,r7000
DEVICE_netgear_r7000_PACKAGES:=kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3
DEVICE_netgear_r7900_NAME:=NETGEAR R7900
DEVICE_netgear_r7900_HAS_IMAGE_METADATA:=0
DEVICE_netgear_r7900_SUPPORTED_DEVICES:=netgear,r7900
DEVICE_netgear_r7900_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-43602a1-pcie kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_netgear_r8000_NAME:=NETGEAR R8000
DEVICE_netgear_r8000_HAS_IMAGE_METADATA:=0
DEVICE_netgear_r8000_SUPPORTED_DEVICES:=netgear,r8000
DEVICE_netgear_r8000_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-43602a1-pcie kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_netgear_r8500_NAME:=NETGEAR R8500
DEVICE_netgear_r8500_HAS_IMAGE_METADATA:=0
DEVICE_netgear_r8500_SUPPORTED_DEVICES:=netgear,r8500
DEVICE_netgear_r8500_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-4366b1-pcie kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_smartrg_sr400ac_NAME:=SmartRG SR400ac
DEVICE_smartrg_sr400ac_HAS_IMAGE_METADATA:=0
DEVICE_smartrg_sr400ac_SUPPORTED_DEVICES:=smartrg,sr400ac
DEVICE_smartrg_sr400ac_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-43602a1-pcie kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_phicomm_k3_NAME:=Wavlink QUANTUM DAX (PHICOMM K3)
DEVICE_phicomm_k3_HAS_IMAGE_METADATA:=0
DEVICE_phicomm_k3_SUPPORTED_DEVICES:=phicomm,k3
DEVICE_phicomm_k3_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-4366c0-pcie kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_phicomm_k3_NAME:=Wavlink WL-WN538A8 (PHICOMM K3)
DEVICE_phicomm_k3_HAS_IMAGE_METADATA:=0
DEVICE_phicomm_k3_SUPPORTED_DEVICES:=phicomm,k3
DEVICE_phicomm_k3_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-4366c0-pcie kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_phicomm_k3_NAME:=PHICOMM K3
DEVICE_phicomm_k3_HAS_IMAGE_METADATA:=0
DEVICE_phicomm_k3_SUPPORTED_DEVICES:=phicomm,k3
DEVICE_phicomm_k3_PACKAGES:=wpad-basic-mbedtls kmod-brcmfmac brcmfmac-firmware-4366c0-pcie kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport kmod-usb3 kmod-phy-bcm-ns-usb3 iwinfo
DEVICE_tenda_ac9_NAME:=Tenda AC9
DEVICE_tenda_ac9_HAS_IMAGE_METADATA:=0
DEVICE_tenda_ac9_SUPPORTED_DEVICES:=tenda,ac9
DEVICE_tenda_ac9_PACKAGES:=wpad-basic-mbedtls kmod-b43 kmod-usb-ohci kmod-usb2 kmod-phy-bcm-ns-usb2 kmod-usb-ledtrig-usbport iwinfo
